apiVersion: v2
name: traefik-ingress
version: 1.0.2
kubeVersion: ">= 1.16.0-0"
appVersion: 2.3.1
description: "A Kubernetes Ingress Controller based on Traefik"
type: application
keywords:
  - traefik
  - ingress
home: https://github.com/mia-platform/helm-charts
sources:
  - https://github.com/containous/traefik
maintainers:
  - name: "Jacopo Andrea Giola"
    url: https://github.com/JGiola
icon: https://docs.traefik.io/assets/img/traefik.logo.png
deprecated: false
