{{- if .Values.defaultLogging.enabled -}}
{{- $ca := genCA "svc-cat-ca" 3650 -}}
{{- $cn := printf "%s.%s.svc.cluster.local" (include "mia-logging.loggingFluentdName" .) .Release.Namespace -}}
{{- $server := genSignedCert $cn nil nil 365 $ca -}}
{{- $client := genSignedCert "" nil nil 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mia-logging.loggingFluentdSecretName" . }}
  labels:
    {{- include "mia-logging.labels" . | nindent 4 }}
data:
  ca.crt: {{ b64enc $ca.Cert | quote }}
  tls.crt: {{ b64enc $server.Cert | quote }}
  tls.key: {{ b64enc $server.Key | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mia-logging.loggingFluentbitSecretName" . }}
  labels:
    {{- include "mia-logging.labels" . | nindent 4 }}
data:
  ca.crt: {{ b64enc $ca.Cert | quote }}
  tls.crt: {{ b64enc $client.Cert | quote }}
  tls.key: {{ b64enc $client.Key | quote }}
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ include "mia-logging.fullname" . | quote }}
  labels: &Labels
    {{- include "mia-logging.labels" . | nindent 4 }}
  {{- with .Values.deploy.annotations }}
  annotations: &Annotations
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  enableRecreateWorkloadOnImmutableFieldChange: true
  loggingRef: ""
  flowConfigCheckDisabled: false
  flowConfigOverride: ""
  controlNamespace: {{ .Release.Namespace | quote }}
  fluentbit:
    tls:
      enabled: true
      secretName: {{ include "mia-logging.loggingFluentbitSecretName" . | quote }}
      sharedKey: {{ .Values.defaultLogging.sharedKey | quote }}
    labels:
      {{- include "mia-logging.selectorLabels" . | nindent 6 }}
    image:
      repository: {{ include "mia-logging.fluentbitImageName" . | quote }}
      tag: {{ include "mia-logging.fluentbitImageVersion" . | quote }}
    filterKubernetes:
      Merge_Log: "Off"
      Labels: "On"
      Annotations: "On"
      K8S-Logging.Exclude: "On"
    inputTail:
      Path: {{ .Values.defaultLogging.fluentbit.logFilesPattern | quote }}
      Mem_Buf_Limit: "10MB"
      Refresh_Interval: "30"
      Rotate_Wait: "30"
    positiondb:
      hostPath:
        path: "/var/log/logging-operator"
    metrics:
      serviceMonitor: {{ .Values.enableServiceMonitor }}
      prometheusAnnotations: false
      port: 2020
      path: "/api/v1/metrics/prometheus"
      timeout: "30s"
      interval: "15s"
    {{- with .Values.defaultLogging.fluentbit.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    security:
      roleBasedAccessControlCreate: true
      podSecurityPolicyCreate: {{ .Values.podSecurityPolicyEnabled }}
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        privileged: false
        capabilities:
          drop:
            - "all"
      podSecurityContext:
        {{- include "mia-logging.fluentbitUserId" . | nindent 8 }}
        runAsGroup: 11000
        fsGroup: 12000
    annotations:
      checksum/config: {{ $client.Cert | sha256sum | quote }}
    {{- with .Values.defaultLogging.fluentbit.annotations }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentbit.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentbit.nodeSelectors }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentbit.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  fluentd:
    tls:
      enabled: true
      secretName: {{ include "mia-logging.loggingFluentdSecretName" . | quote }}
      sharedKey: {{ .Values.defaultLogging.sharedKey | quote }}
    labels:
      {{- include "mia-logging.selectorLabels" . | nindent 6 }}
    image:
      repository: {{ include "mia-logging.fluentdImageName" . | quote }}
      tag: {{ include "mia-logging.fluentdImageVersion" . | quote }}
    scaling:
      replicas: {{ .Values.defaultLogging.fluentd.replicas }}
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: {{ .Values.defaultLogging.fluentd.bufferStorage | quote }}
    livenessDefaultCheck: true
    metrics:
     serviceMonitor: {{ .Values.enableServiceMonitor }}
     prometheusAnnotations: false
     port: 24231
     path: "/metrics"
     timeout: "30s"
     interval: "15s"
    {{- with .Values.defaultLogging.fluentd.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    security:
      roleBasedAccessControlCreate: true
      podSecurityPolicyCreate: {{ .Values.podSecurityPolicyEnabled }}
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        privileged: false
        capabilities:
          drop:
            - "all"
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
    annotations:
      checksum/config: {{ $server.Cert | sha256sum | quote }}
    {{- with .Values.defaultLogging.fluentd.annotations }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentd.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentd.nodeSelectors }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentd.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
