{{- if .Values.podSecurityPolicyEnabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "logging.fullname" . | quote }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "docker/default"
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  "docker/default"
spec:
  readOnlyRootFilesystem: true
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - "ALL"
  volumes:
    - "configMap"
    - "secret"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: "MustRunAs"
    ranges:
      - min: 10000
        max: 10000
  seLinux:
    rule: "RunAsAny"
  supplementalGroups:
    rule: "MustRunAs"
    ranges:
      - min: 11000
        max: 11000
  fsGroup:
    rule: "MustRunAs"
    ranges:
      - min: 12000
        max: 12000
{{- end -}}
