{{- if .Values.defaultLogging.enabled -}}
{{- $ca := genCA "svc-cat-ca" 3650 -}}
{{- $cn := printf "%s.%s.svc.cluster.local" (include "logging.loggingFluentdName" .) .Release.Namespace -}}
{{- $server := genSignedCert $cn nil nil 365 $ca -}}
{{- $client := genSignedCert "" nil nil 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logging.loggingFluentdSecretName" . }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
data:
  ca.crt: {{ b64enc $ca.Cert | quote }}
  tls.crt: {{ b64enc $server.Cert | quote }}
  tls.key: {{ b64enc $server.Key | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logging.loggingFluentbitSecretName" . }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
data:
  ca.crt: {{ b64enc $ca.Cert | quote }}
  tls.crt: {{ b64enc $client.Cert | quote }}
  tls.key: {{ b64enc $client.Key | quote }}
{{- end -}}
