apiVersion: v1
kind: Service
metadata:
  name: {{ include "logging.fullname" . | quote }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "logging.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: web
      protocol: TCP
      name: web
