{{- if .Values.podSecurityPolicyEnabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "mia-monitoring.nodeExporter.fullname" . | quote }}
  labels:
    {{- include "mia-monitoring.nodeExporter.labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "docker/default,runtime/default"
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  "docker/default,runtime/default"
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - "secret"
    - "hostPath"
  hostNetwork: true
  hostIPC: false
  hostPID: true
  runAsUser:
    rule: "MustRunAs"
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: "RunAsAny"
  supplementalGroups:
    rule: "MustRunAs"
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: "MustRunAs"
    ranges:
      - min: 1
        max: 65535
{{- end -}}
