{{- if .Values.podSecurityPolicyEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "monitoring.nodeExporter.roleName" . | quote }}
  labels:
    {{- include "monitoring.nodeExporter.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "policy"
    resources:
      - "podsecuritypolicies"
    verbs:
      - "use"
    resourceNames:
      - {{ include "monitoring.nodeExporter.fullname" . | quote }}
{{- end -}}
