{{- if .Values.podSecurityPolicyEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "monitoring.nodeExporter.roleName" . | quote }}
  labels:
    {{- include "monitoring.nodeExporter.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: {{ include "monitoring.nodeExporter.roleName" . | quote }}
subjects:
  - kind: "ServiceAccount"
    name: {{ include "monitoring.nodeExporter.serviceAccountName" . | quote }}
    namespace: {{ .Release.Namespace | quote }}
{{- end -}}
