{{- if and (semverCompare ">=1.18-0" .Capabilities.KubeVersion.Version) (semverCompare ">=2.3" (( include "mia-traefik-ingress.version" . ))) -}}
{{- if semverCompare "< 1.19-0" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end -}}
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.defaultIngressClass | quote }}
  labels:
    {{- include "mia-traefik-ingress.labels" . | nindent 4 }}
  name: {{ include "mia-traefik-ingress.fullname" . | quote }}
spec:
  controller: "traefik.io/ingress-controller"
{{- end }}
