{{- if .Values.podDisruptionBudgetEnabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mia-traefik-ingress.fullname" . | quote }}
  labels:
    {{- include "mia-traefik-ingress.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{- include "mia-traefik-ingress.selectorLabels" . | nindent 6 }}
{{- end }}
