apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "logging.roleName" . | quote }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "alertmanagers"
      - "prometheuses"
      - "prometheuses/finalizers"
      - "alertmanagers/finalizers"
      - "servicemonitors"
      - "podmonitors"
      - "prometheusrules"
      - "podmonitors"
    verbs:
      - "*"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "list"
      - "watch"
  - apiGroups:
      - "logging.banzaicloud.io"
    resources:
      - "loggings"
      - "flows"
      - "clusterflows"
      - "outputs"
      - "clusteroutputs"
    verbs:
      - "create"
      - "delete"
      - "get"
      - "list"
      - "patch"
      - "update"
      - "watch"
  - apiGroups:
      - "logging.banzaicloud.io"
    resources:
      - "loggings/status"
    verbs:
      - "get"
      - "patch"
      - "update"
  - apiGroups:
      - ""
      - "apps"
      - "batch"
      - "extensions"
      - "policy"
      - "rbac.authorization.k8s.io"
    resources:
      - "namespaces"
      - "nodes"
      - "persistentvolumeclaims"
      - "pods"
      - "services"
      - "resourcequotas"
      - "replicationcontrollers"
      - "limitranges"
      - "persistentvolumeclaims"
      - "persistentvolumes"
      - "endpoints"
      - "secrets"
      - "configmaps"
      - "serviceaccounts"
      - "roles"
      - "rolebindings"
      - "clusterroles"
      - "clusterrolebindings"
      - "podsecuritypolicies"
      - "daemonsets"
      - "deployments"
      - "replicasets"
      - "statefulsets"
      - "jobs"
    verbs:
      - "*"
  - apiGroups:
      - "extensions"
      - "policy"
    resources:
      - "podsecuritypolicies"
    verbs:
      - "list"
      - "get"
{{- if .Values.podSecurityPolicyEnabled }}
  - apiGroups:
      - "policy"
    resources:
      - "podsecuritypolicies"
    verbs:
      - "use"
    resourceNames:
      - {{ include "logging.fullname" . }}
{{- end }}
