apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ include "monitoring.alertmanager.fullname" . | quote }}
  labels:
    {{- include "monitoring.alertmanager.labels" . | nindent 4 }}
  {{- with .Values.deploy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceAccountName: {{ include "monitoring.alertmanager.serviceAccountName" . }}
  image: {{ include "monitoring.alertmanager.image" . | quote }}
  {{- with .Values.deploy.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | indent 4 }}
  {{- end }}
  replicas: {{ .Values.alertmanager.replicas }}
  {{- with .Values.alertmanager.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 11000
    fsGroup: 12000
  logLevel: {{ .Values.logLevel | quote }}
  logFormat: "json"
  externalUrl: "http://{{ include "monitoring.alertmanager.fullname" . }}.{{ .Release.Namespace }}:9093"
  paused: false
  listenLocal: false
  portName: "web"
  retention: "120h"
  routePrefix: "/"
  {{- if .Values.alertmanager.config }}
  configSecret: {{ include "monitoring.alertmanager.configSecret" . | quote }}
  {{- end }}
  alertmanagerConfigSelector: {}
  alertmanagerConfigNamespaceSelector: {}
  {{- with .Values.alertmanager.storageSpec }}
  storage:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  podMetadata:
    labels:
      {{- include "monitoring.alertmanager.selectorLabels" . | nindent 6 }}
    {{- with .Values.deploy.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  affinity:
    {{- include "monitoring.alertmanager.podAffinity" . | nindent 4 }}
  {{- with .Values.alertmanager.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.alertmanager.tolerations }}
  tolerations:
    {{ toYaml . | indent 4 }}
  {{- end }}
