{{- if .Values.alertmanager.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mia-monitoring.alertmanager.configSecret" . | quote }}
  labels:
    {{- include "mia-monitoring.alertmanager.labels" . | nindent 4 }}
  {{- with .Values.deploy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  alertmanager.yaml: {{ toYaml .Values.alertmanager.config | b64enc | quote }}
{{- end -}}
