apiVersion: v1
kind: Service
metadata:
  name: {{ include "mia-monitoring.alertmanager.fullname" . | quote }}
  labels:
    {{- include "mia-monitoring.alertmanager.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "mia-monitoring.alertmanager.selectorLabels" . | nindent 4 }}
  ports:
    - port: 9093
      targetPort: "web"
      protocol: TCP
      name: "web"
