apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . | quote }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
  ports:
    - port: 443
      targetPort: websecure
      protocol: TCP
      name: websecure
