apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "traefik-ingress.serviceAccountName" . | quote }}
  labels:
    {{- include "traefik-ingress.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
