apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "mia-monitoring.alertmanager.fullname" . | quote }}
  labels:
    {{- include "mia-monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mia-monitoring.alertmanager.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  jobLabel: "app.kubernetes.io/name"
  podMetricsEndpoints:
    - port: "web"
      path: "/metrics"
    - port: "reloader-web"
      path: "/metrics"
