{{- if .Values.prometheus.enableDNSMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "mia-monitoring.dns.fullname" . | quote }}
  labels:
    {{- include "mia-monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      k8s-app: "kube-dns"
  namespaceSelector:
    matchNames:
      - "kube-system"
  jobLabel: "k8s-app"
  podMetricsEndpoints:
    - port: "metrics"
{{- end }}
