apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "monitoring.prometheus.fullname" . | quote }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "monitoring.prometheus.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  jobLabel: "app.kubernetes.io/name"
  podMetricsEndpoints:
    - port: "web"
      path: "/metrics"
